### PR TITLE
demo: enforce no top level await in utilities; refactor user.js

### PR DESCRIPTION
**Pull request by marcustyphoon**
### Description

this still breaks intellisense on user.js exports unless you do ridiculous things with it, come on

### CODE REVIEW

**Comment by AprilSylph** [comment]
to fix intellisense, can you define a custom jsdoc type and then annotate the function as returning that?

**Comment by AprilSylph** [comment]
also, this PR title (and current contents) has me worried that you're doing too much at once - I think 5746d0dc1ae5da9375e356177653308ec7a4e817 is PR-sized by itself

**Comment by marcustyphoon** [comment]
Was more trying to demo what I was thinking and setting up a test to see if it actually works. I don't know what path you want to take right now; are you still thinking about doing this transformation on all 7 relevant utility files wherever they are imported? I don't think I would do that.

**Comment by AprilSylph** [comment]
what's the alternative?

**Comment by marcustyphoon** [comment]
Among other things, pre-importing utils that contain top-level await, as shown in this PR. ```await Promise.all(['css_map', 'language_data'].map(name => import(getURL(`/util/${name}.js`))));```

**Comment by AprilSylph** [comment]
I'm not a fan of that because that means potentially importing utils that aren't used by any enabled features.

**Comment by AprilSylph** [comment]
I will admit that it is a less invasive modification though... is there a PR for doing just that? I'll accept it as an immediate solution, then we can discuss longer-term solutions afterwards.

**Comment by marcustyphoon** [comment]
Yep. That's what I was illustrating/proposing here: the use of special case logic for css map and language specifically, as they are nontrivially used in other utils. There are certainly ways to configure the extension such that no `window.tumblr` utilities are required for all enabled features to function, but they seem quite rare to me.

From the standpoint of the design reflecting this framing, it feels reasonable to me to obtain a reference to these core APIs during the boot process. I couldn't figure out a way to pass this down to dynamically imported js files without setting a property on `window` in the initialization script and figuring out how to make intellisense work on a a global, however, which is obviously awkward. (Apparently you need to use typescript syntax for VS Code to accept it; also, globals = eew, etc.)

> is there a PR for doing just that? I'll accept it as an immediate solution, then we can discuss longer-term solutions afterwards.

Will do!

**Pull request closed without merging**
