### PR TITLE
Trim Reblogs: Add info popup in editor

### PR DESCRIPTION
**Pull request by marcustyphoon**
just a totally random idea I had; opinions?

### Description

Adds an informational element to the post editor in the general area where the old Editable Reblogs button was that is only shown when the user mouses over that area, explaining that Trim Reblogs must be used after posting.

Could also make it appear normally, with a `hide [X]` button at the bottom, which would save a flag in local storage and either trigger this mode or just get rid of it.

If there is a nonzero chance that gutenblr gets proper trail trimming, definitely do not merge this.

I am bad at CSS.

### Testing steps

Open gutenblr and mouse under the user avatar on the left side of the screen.

### CODE REVIEW

**Comment by AprilSylph** [comment]
> If there is a nonzero chance that gutenblr gets proper trail trimming, definitely do not merge this.

😉

**Comment by marcustyphoon** [comment]
👀👀👀

**Comment by AprilSylph** [comment]
wait, nevermind, someone got convinced that Editable Reblogs was a native feature of the legacy editor lmao

**Comment by marcustyphoon** [comment]
Undrafting this because, look, whatever, I don't know. Graphic design is my passion but this does fill me with, you know, job well done vibes.

**Comment by AprilSylph** [comment]
I think the new Trim Reblogs description is sufficient.

**Pull request closed without merging**
