### PR TITLE
create softNavigate utility

### PR DESCRIPTION
**Pull request by marcustyphoon**
¯\\\_(ツ)\_/¯ 

#### User-facing changes
- 

#### Technical explanation
Creates a utility that steals the useNavigate router hook from from Tumblr's internals, enabling XKit Rewritten to simulate arbitrary soft navigation.

### CODE REVIEW

**Comment by AprilSylph** [comment]
POG?

**Comment by AprilSylph** [comment]
Oh I see, right of course there are still some non-functional components that can't use hooks and so need `navigate` as a prop... So this would depend on us finding a part of the React tree that has such a component in it and hoping it doesn't get converted to functional.

**Comment by marcustyphoon** [comment]
Yeah, I haven't looked at whether funding component hooks are possible to grab externally. It looked like, iirc, the buttons to compose a post, the search form, part of the messaging system, and... I forget what the other one was... had it in props.

**Comment by marcustyphoon** [comment]
I was not successful in finding another way to do this if `navigate` is eventually removed from all props. I guess we have to just hope `componentDidCatch` never gets a hook version if we want to use this*. Fun fact, though: `document.querySelector('title')` also works, though I'm not actually sure why the relevant component has a WithRouter on it.

*this is a joke, pls error boundary hook im begging

**Comment by AprilSylph** [comment]
It would probably be more useful to just pitch exposing `navigate` on the global `tumblr` object. I can't imagine that triggering route loads can be any more dangerous than, you know, what we do already with making fully-authenticated API requests.

**Comment by marcustyphoon** [comment]
Yeah, that's certainly the practical upshot. I don't think I would want to rely on this otherwise unless the fallback hard navigation/open-in-new-tab wasn't really a downside.

**Comment by AprilSylph** [comment]
I spent about an hour today trying to extract `navigate` out of its hook and into `window.tumblr` but either I need to change how the object is built (we're using a non-React class, for some reason...) or I need to learn a trick to steal hook outputs and dump them. Memory references to already-rendered components in the React code itself sadly does not allow you to read their props, unless there's some method that wouldn't be exposed by logging the whole thing to the console. (Maybe some method on the prototype I'm not aware of...?)

**Comment by marcustyphoon** [comment]
Yep, I see. The function we want wouldn't exist before hydration anyway, I assume, and if I'm skimming the code correctly, `window.tumblr` gets attached independent of that. Presumably it would have to be moved into a side effect on a component that's inside the `<Router>`?

(I noticed that React Router's `history` object gets created independently, given that `window.tumblr.on()` and `window.tumblr.off()` call `history.listen`; it looks like simply exposing `history.push` wouldn't work, though. And even if it did, that sounds pretty bad.)

**Pull request closed without merging**
