### PR TITLE
Tag Tracking+: Remove ads/recommendations from api response

### LINKED ISSUE #691: Tag Tracking+ incorrect unread counts
### Platform

Windows 11

### Browser

Firefox 103.0.1

### Addon version

0.20.05 beta

### Details

Whenever there are new posts in a tag I'm tracking the number displayed for unread posts never increases beyond 2.

### PR DESCRIPTION
**Pull request by marcustyphoon**
#### User-facing changes
- Prevents Tag Tracking+ new posts counts from stopping at two.

#### Technical explanation
There are ad posts in the API response for /v2/hubs/[tag]/timeline.

It seemed like the simplest way to filter these out was simply to ensure that only posts tagged with the tag in question are counted, so I did that. 

Here are some unique keys from the house ad post object I looked at that are not contained in a regular post, in case a different method is needed/for future reference:

```json
        "displayType": 1,
        "sponsoredBadgeUrl": "https://www.tumblr.com/docs/en/relevantads",
        "admMediaType": "tsp-display",
        "adm": {},
        "price": 0,
        "adProviderId": "smart",
        "adProviderPlacementId": null,
        "adProviderForeignPlacementId": "1623962",
        "adProviderInstanceId": "4bfcd452-5de3-4c3f-ba05-8d88d711f5fc",
        "adRequestId": "9b2d47bc-f9bb-4026-a5f2-ac02a949b23e",
        "adInstanceId": "60708e80-1281-418c-b2b9-b30eac82e521",
        "adInstanceCreatedTimestamp": 1659747342240,
        "fillId": null,
        "advertiserId": "472420",
        "campaignId": "2067986",
        "adGroupId": "10846686",
        "adId": "28198847",
        "creativeId": "28198847",
        "supplyOpportunityInstanceId": "109b87ab-42d8-4733-8c93-add30d733c2c",
        "mediationCandidateId": "8bbc0010-d90f-43d1-97c6-cb0e8ef567f4",
        "supplyRequestId": "004ad99deed4da08f1ce17a2f973cc14",
        "supplyProviderId": "communityhub",
        "actions": [
            {
                "type": "cta",
                "text": "Shop now",
                "animate": false,
                "urls": {},
                "buttonBackgroundColor": "",
                "buttonTextColor": "",
                "buttonBorderColor": "",
                "brandAvatarUrl": "",
                "displayUrl": "",
                "tspSkipLightbox": true,
                "backgroundColor": "#00B8FF",
                "textColor": "#ffffff",
                "borderColor": "#00B8FF"
            }
        ],
```

#### Issues this closes
Resolves #691

### CODE REVIEW

**Comment by marcustyphoon** [comment]
Ah, crap, there is also `recommendedSource: "🎊 New arrival"`. Lovely.

**Comment by AprilSylph** [comment]
Something else is going wrong here. I'm seeing a tracked tag be at 15+ unread, then I visit the tag, and the unread count becomes 10 instead. Probably just needs a similar adjustment to the post-seeing logic.

**Comment by AprilSylph** [comment]
Yup, house ads on the (masonry-style, at least) hub pages are getting processed.

**Comment by marcustyphoon** [comment]
Oh right. That feels like it should have been obvious to me :D Feel free to implement this yourself if you'd like, or I'll do it sometime next week.

**Comment by AprilSylph** [comment]
Well, 15+ goes to 0 correctly now, time to wait for people to make more posts in the `#cats` tag to make sure that the number goes _up_ again correctly.

**Review by AprilSylph — APPROVED** [review]
Can now verify that counts go up correctly.

**Pull request merged**
