### PR TITLE
Quote Replies: Activate in notification dropdown

### LINKED ISSUE #862: Quote Replies: Activate in notification dropdown
### Concept

Quote Replies works on the activity page, but not in the activity dropdown. I see the necessary React data in both places, so I assume this should be fairly easy to implement? Or was there a technical reason why this isn't already doable?

### PR DESCRIPTION
**Pull request by marcustyphoon**
### Description

Adds Quote Replies buttons to the activity dropdown.

idk man. css or whatever. there's not a lot of space in there

Resolves #862.

### Testing steps

Use Quote Replies on the activity page. Confirm that it still works as expected.
Use Quote Replies from the notification dropdown. Confirm that it works as expected.
Comment the `@media (hover: hover)` CSS rule section or use a touchscreen and confirm that nothing explodes and the Quote Replies buttons are still visible.

### CODE REVIEW

**Comment by marcustyphoon** [comment]
- [ ] don't process the notification counters on blog avatars in the blog selector dropdown inside the activity dropdown (causing a silent error)

See, this is why error messages on uncaught promise rejections are useful!

**Comment by AprilSylph** [comment]
I think rather than any of the proposed CSS, I would just do...

```css
button.xkit-quote-replies-dropdown {
  align-self: flex-start;
  margin: 10px 0 0;
  transform: none;
}
```

and remove the `-activity` classname. would commit myself, but am sleepytired. good night

**Comment by marcustyphoon** [comment]
Would you leave the fade-unless-hovered effect or leave it?

**Comment by AprilSylph** [comment]
Between leaving it and leaving it 🤔 I would leave it

(I prefer the consistent behaviour of having the button hide itself regardless of location)

**Comment by marcustyphoon** [comment]
Hah, whoops.

**Review by AprilSylph — APPROVED** [review]

**Comment by AprilSylph** [comment]
> Comment the @media (hover: hover) CSS rule section or use a touchscreen and confirm that nothing explodes and the Quote Replies buttons are still visible.

This is the funniest way to learn that Chromium's responsive design mode doesn't have a simple touch simulation toggle. I've been listing "[enable/disable] touch simulation" as a testing step on Redpop PRs for months, I guess I'll try to say "simulate a touchscreen device" instead from now on.

**Comment by marcustyphoon** [comment]
I was going to say you were right, but then I checked: press the three dots -> "add device type!"

**Pull request merged**
