### PR TITLE
Tweaks: Remove unread post count from tab title

### LINKED ISSUE #1360: Correct notification count in tab title when ignoring unread following posts
### Concept

The `Hide the Home/Following unread badge` tweak currently only hides the actual badge via css. This has the downside of leaving the actual browser tab title unaffected, which is constantly updated to `(n) Tumblr`, where `n` is the inbox + unread count.  
image
It would be nice if the Unread count was ignored here too, although this would of course increase the complexity of the patch from a simple css inject.  
Since realistically, noone would want the Unread badge hidden but the unread count included in the window title, this should likely not be a separate patch, but an update of the exisitng one.  
*The easiest way to accomplish both badge hiding and the window title fix is probably patching the `unread` field in the `/counts` response to `0`. This would also make the badge hiding immune to tumblr css changes.*

*My apologies if this is what is meant by the "Tab titles" entry in the `Feature Progress/unplanned` board, but it's pretty ambiguous*

### PR DESCRIPTION
**Pull request by marcustyphoon**
### Description

As discussed and prototyped in the linked issue, this is April's code that adds functionality to the `Hide the Home/Following unread badge` tweak to also hide the unread post count in the browser tab title.

Resolves #1360.

### CODE REVIEW

**Comment by marcustyphoon** [comment]
I think it would probably make sense to adjust the name of the tweak as well. Something like `Hide the unread post count in the`—ugh I don't know how to make it succinct.

**Comment by AprilSylph** [comment]
I think `Hide the Home/Following unread count` would make sense. Previously it was limited to the badge, now it hides the count everywhere... right?

**Comment by marcustyphoon** [comment]
I don't think people who are looking for it because they don't like it being in the tab titles will find it that way, but yeah.

**Review by AprilSylph — CHANGES_REQUESTED** [review]
https://github.com/AprilSylph/XKit-Rewritten/pull/1397#issuecomment-1930807363

i maintain that "unread count" makes way more sense now

**Review by AprilSylph — APPROVED** [review]

**Pull request merged**
