### PR TITLE
Mutual Checker: Tooltip on mutuals icon

### PR DESCRIPTION
**Pull request by marcustyphoon**
### Description

This adds an on-hover tooltip to the mutual checker icon. (The text is based on that of Tumblr's built-in one.)

Not sure why the duplicated xmlns attribute is needed?

### Testing steps

Hover the mouse over the mutual checker icon. A tooltip should appear.

### CODE REVIEW

**Comment by AprilSylph** [comment]
Oh hey, I tried to add this and failed. Didn't know `title` was an SVG element (I tried using an attribute).

Can we not co-opt Tumblr's translation string for this?

**Comment by marcustyphoon** [comment]
Good point! Let me check. Guessing no.

```json
    "Mutuals for a year": "Ihr folgt euch seit einem Jahr",
    "Mutuals for less than a year": "Ihr folgt euch seit weniger als einem Jahr",

    "Following each other for %1$s day": "Ihr folgt einander seit %1$s Tag",
    "Following each other for %1$s hour": "Ihr folgt einander seit %1$s Stunde",
    "Following each other for %1$s minute": "Ihr folgt einander seit %1$s Minute",
    "Following each other for %1$s second": "Ihr folgt einander seit %1$s Sekunde",
    "Following each other for %1$s year": "Ihr folgt einander seit %1$s Jahr",
    "Following each other since just now": "Ihr folgt einander seit gerade eben",

    "Not following each other": "Ihr folgt euch nicht",
```

Yeah, looks like not, unfortunately. (I have had some fun trying to adjust the translated grammar for a "notes" button in a script that hid the note count but kept the button, but it didn't work. The translators change the phasing a ton, grammar aside.)

**Comment by marcustyphoon** [comment]
```js
apiFetch(`/v2/blog/${blogName}/info?fields[blogs]=?is_following_you,?duration_blog_following_you, ?duration_following_blog`);
```
Okay, well, that totally works. Is this more server load than `/v2/blog/${primaryBlogName}/followed_by`? 

I see you assigned yourself to #889, which I split out for "maybe we want to merge this one and leave that one for a long time since idk how to do it" reasons, and the refactoring in that one means it would be silly to commit changes here.

**Comment by AprilSylph** [comment]
re: translations, what do you think of using the "[blogname/] follows you!" string? (The confirmation text from when you follow-check someone from your followers page.) Personally I don't think it's super important to specify that you're _mutuals_ specifically.

**Comment by marcustyphoon** [comment]
Yeah, that sounds reasonable!

**Comment by marcustyphoon** [comment]
Adding this to #889 to avoid merge conflicts.

**Pull request closed without merging**
