### PR TITLE
Open in Tabs: Fix interaction with Tumblr Patio UI

### LINKED ISSUE #1371: Open in Tabs breaks Tumblr Patio blog column addition
### Platform

MacOS 14.2.1 arm64

### Browser

Chrome 120.0.6099.216

### Addon version

0.23.3

### Details

As per a post: https://www.tumblr.com/whatjanesays/739869476461363200

Open in Tabs intercepts a click in part of the Tumblr Patio UI that's used to add a blog column.

### PR DESCRIPTION
**Pull request by marcustyphoon**
### Description

Prevents Open in Tabs from intercepting a click in part of the "Tumblr Patio" feature preview UI that's used to add a blog column.

Resolves #1371.

### Testing steps

- Enable Open in Tabs.
- In Tumblr Patio, add a blog column and confirm that selecting the desired blog works correctly.
- Make sure that... it still... works as much as it did before otherwise? I dunno; I don't use the script.

### CODE REVIEW

**Review by AprilSylph — CHANGES_REQUESTED** [review]
- Type a blog name (e.g. `pyoro`) into the site's search bar
- Click any of the blog results that have avatars (i.e. are not the "Go to @{blogName}" result)
  - **Production result**: The blog is opened in a new tab
  - **PR result**: The blog is opened in the blog view

Can the exclusion selector be made more specific to Patio?

**Comment by marcustyphoon** [comment]
Ah, shoot. Let me check.

**Comment by marcustyphoon** [comment]
Indeed it can be. This is why we have review, people!

**Comment by marcustyphoon** [comment]
Re-performed testing myself; seems to work as expected.

**Comment by marcustyphoon** [comment]
@AprilSylph This being a oneliner, may I request a merge-without-formal-review and version release?

**Review by AprilSylph — APPROVED** [review]

**Comment by AprilSylph** [comment]
I was about to test this anyway, so I did.

Will do a release once this is merged (if that's what you're asking for), although it's late for me so that will likely end up being tomorrow.

**Pull request merged**
