### PR TITLE
CleanFeed: Always process mature-labeled posts

### LINKED ISSUE #947: CleanFeed: Integrate with community labels
### Concept

Flagged blogs still exist, but they are mostly superseded by community labels. CleanFeed should integrate with this. (Making media blurred is a distinctly different experience than having to click to unhide the entire post, tags and all; I strongly view this as worth doing despite the "blur" native Tumblr option).

Thinking about the preference UI for this, my first thought is a list of checkboxes for e.g. flagged blogs, mature-flagged posts, sexual-flagged posts, violence-flagged posts, etc. This is pretty complicated, though, and realistically seems almost entirely pointless.

Including posts with any community label along with posts from flagged blogs seems like the simplest solution, albeit one that needs new preference UI copy.

Thoughts; suggestions?

### PR DESCRIPTION
**Pull request by marcustyphoon**
### Description

This includes mature-labeled posts along with posts by "flagged" blogs in CleanFeed. It doesn't add any additional options or process nudity/violence/alcohol flags separately, opting for the simplest solution.

Resolves #947.

### CODE REVIEW

**Review by AprilSylph — CHANGES_REQUESTED** [review]
not too happy with the copy, "flagged media" is taken-down media

my suggestion:

---

**Hide media in posts:**
- When the post or post author is marked for mature content
- Always

**Always hide media from these blogs (comma-separated)**
```

```

**Comment by marcustyphoon** [comment]
I like the clarity, but I don't think we can put a string that long in a dropdown. We could redesign it to a checkbox, but I don't think that's clear either. Hm.

**Comment by AprilSylph** [comment]
copy suggestion v2

---

Hide media from
- mature posts & blogs
- all posts

**Comment by marcustyphoon** [comment]
Perfect, that fits nicely!

**Comment by AprilSylph** [comment]
forgot to add a suggestion for the manual flagging:
```diff
- Treat these blogs as flagged (comma-separated)
+ Treat these blogs as mature (comma-separated)
```

**Review by AprilSylph — APPROVED** [review]

**Pull request merged**
