### PR TITLE
Quote Replies: Fix functionality on "Tumblr Patio" preview

### LINKED ISSUE #1368: Quote Replies: Nonfunctional on "Tumblr Patio" preview
### Platform

MacOS 14.2.1 arm64

### Browser

Chrome 120.0.6099.216

### Addon version

0.23.3

### Details

Quote Replies doesn't function in the "Tumblr Patio" feature preview.

It should probably use the `notificationSelector` exported in #1306... and we should also make that selector more specific, as right now it also incorrectly selects some elements in the dropdown that you use to select a blog to see the activity of... you know what, a picture is more illustrative:

### PR DESCRIPTION
**Pull request by marcustyphoon**
### Description

This fixes the selection of notification elements used in Quote Replies so that it's a) consistent with NotificationBlock, and b) works on activity columns in the "Tumblr Patio" feature preview.

Resolves #1368.

It also fixes an error that would appear in the js console when you opened this menu with NotificationBlock enabled, as it erroneously selected an element in that menu:

This relies a lot on `aria-role`.

### Testing steps

- Confirm that Quote Replies and NotificationBlock work on an activity column in Tumblr Patio, in the activity modal, and on the activity page.

### CODE REVIEW

**Comment by nightpool** [comment]
I can test on Patio if you want

**Comment by marcustyphoon** [comment]
> No apparent regressions. Can't test on Patio; don't have it!

Wait, do you not get your personal account automatically dogfooded into this kind of thing?

**Comment by AprilSylph** [comment]
Nope! I decided to make a new account for work-related stuff. That account gets all the staff privileges, while my personal and testing accounts don't. Whitelisting them for new features is as manual a process as whitelisting other XKit devs.

**Comment by marcustyphoon** [comment]
Makes sense! Although, I mean, your testing account *is* the testing account of an XKit dev... :D 

Oh, wait, I guess it probably doesn't have ad-free, does it. That makes this particular case more complicated. (And I guess that I'm happy my personal account does have Patio, whether that's intentional or lucky.)

**Comment by marcustyphoon** [comment]
I have tested this again and it continues to work as expected, including on Patio.

**Comment by marcustyphoon** [comment]
Treating my own testing as an approval re: patio testing.

**Pull request merged**
