### PR TITLE
NotificationBlock: Add note about "Mute Notifications"

### LINKED ISSUE #1173: NotificationBlock: Mention native option in UI
### Concept

Tumblr has an option to turn notifications off natively now, but it works differently.

The NotificationBlock modal popup should explain this.

### PR DESCRIPTION
**Pull request by marcustyphoon**
### Description

This adds a note to the NotificationBlock interface about the new "Mute Notifications" native feature.

It also—and I'm fine with not doing this if it seems confusing—changes the terminology throughout the NotificationBlock UI to "hide," as the native feature is much closer to what "block" actually means than what the script does. It does not update the name of the script itself, although we could do that too (it would still start with "Notification").

Copy improvement suggestions are welcome.

Resolves #1173.

### Testing steps

n/a

### CODE REVIEW

**Comment by AprilSylph** [comment]
I think I prefer keeping the existing terminology. Putting myself in the shoes of someone who has tried native notification muting and found it not to do what I want, something that promises to _block_ notifications would be much more compelling than something that promises to _hide_ notifications.

**Comment by marcustyphoon** [comment]
Sure thing. Done!

Interesting, though. It's not very obvious to me why that would be the case!

**Comment by AprilSylph** [comment]
I think it's fairly well-established in the social media lexicon that a "Block" is more aggressive than a "Mute" or a "Hide". If muting isn't enough, I want to block!

**Comment by marcustyphoon** [comment]
Ah, gotcha, that's where we're differing: I'm not thinking of this script as more aggressive than the native feature (as it doesn't prevent the notification badge going up and doesn't apply to mobile), while you are. Is what this script brings over/in addition to the native feature just the fact that it's retroactive, or are there notifications that slip through the native one but are "blocked" by this?

**Comment by AprilSylph** [comment]
Just the fact that it's retroactive. I'm thinking in terms of a post breaking containment being like a breaking incident:
- Preventing new notifications is a mitigation. The attack is stopped, but the damage is visible.
- Hiding all notifications is a fix. The damage has been undone, and things can continue as if the attack never happened.

...I'll admit I forgot that the notification badge exists, though. It's always been broken on my account.

**Comment by AprilSylph** [comment]
I won't formally request changes for this because I am actively losing consciousness, but I think the info blurb should explain the difference between the two features in the context of the blocking action, like...

> Unlike Tumblr's option to "Mute notifications", this will not prevent notifications for this post from being created, so they will still increment your unread notification count.

Also, for bonus points, hide the blurb entirely if the post's notifications are already muted. Probably would need an API call? Do we have a cacheless `timelineObject` getter? ouh i feel weird goodnight

**Comment by marcustyphoon** [comment]
> the info blurb should explain the difference between the two features in the context of the blocking action, like...

Agreed!

- [ ] do that

> hide the blurb entirely if the post's notifications are already muted.

Also agreed!

- [ ] that

> Probably would need an API call? Do we have a cacheless `timelineObject` getter?

This one's kind of interesting. Menu items get their `timelineObject` data by default from a query we run in `addPostMeatballItem` when you click the menu, which in some sense is always fresh... except for the fact that that is the menu in which the user would be turning on the feature in question. So if the user opens the menu, mutes the post natively, then clicks on postblock, our data will be outdated; if the user opens the menu, mutes the post, closes the menu, opens the menu, and clicks on postblock, our data will be correct.

I think just doing an API request is simplest here. But yeah, we did remove the unmemoized version of `timelineObject` and it does become a little weird in certain circumstances.

**Review by AprilSylph — APPROVED** [review]

**Pull request merged**
