### PR TITLE
AccessKit Disable GIFs: Use native poster elements 

### LINKED ISSUE #664: AccessKit: pause GIFs using Tumblr's poster elements
GIF posters are out to everyone now, so if GIFs as MP4 have the same poster structure, the whole option could be changed to take advantage of them and implement this in the process.

Otherwise, they will need to be specifically dealt with.

### PR DESCRIPTION
**Pull request by marcustyphoon**
"special cases: the ~~movie~~ xkit extension"

#### User-facing changes
- Fixes disable gifs not working when gifs are served as mp4.

#### Technical explanation
Takes advantage of Tumblr's non-animated "poster" elements that are used to hide gifs while they load... but only in gifs that are part of a post body (currently checking for `figure` elements); other locations where gifs are rendered do not use posters, so the old canvas-based code is still used for those.

A huge mess, basically.

#### Issues this closes
resolves #664

### CODE REVIEW

**Comment by marcustyphoon** [comment]
This appears to do fairly bad things to the foreground/background/postGlass setup in the cardPost element used in the recommended blog carousel, but I'm not sure why at the moment.

**Comment by marcustyphoon** [comment]
Note that `tagImage` elements* and the post previews in the blog cards** do not use gif posters. I don't know about animated `takeoverBanner`s*.

*as of this commit, implemented using the previous canvas-based code. I do not know if these elements can contain mp4 gifs, which would necessitate modification to that code

**just noticed this; not paused as of this commit

**Comment by marcustyphoon** [comment]
Hm. Setting the background color to white requires a really high specificity in the case of the recommended blog carousel, and also doesn't look right. Would probably be more correct to visibility:hidden the background image when not hovered, but to be honest the logic to make that correct sounds like a nightmare, so, eh.

**Comment by AprilSylph** [comment]
> User-facing changes: Fixes disable gifs not working when gifs are served as mp4.

Serving GIFs as MP4 is a dead experiment, so I'm going to close this as unnecessary. Using native GIF posters to pause GIFs is a neat idea for simplifying this option's code, but not worth complicating it for.

**Comment by marcustyphoon** [comment]
👍  If it's ever able to be used for every element, it would be great; given that that is not the case this is absolutely not worth it.

**Pull request closed without merging**
